databases:
  - name: citypulse_db
    databaseName: citypulse
    user: citypulse_user
    plan: free

services:
  - type: web
    name: citypulse
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn citypulse.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: citypulse_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
